import '../css/index.css';
import './sphere.js';
import './Section-wipes--horisontal.js';
import '../css/sphere.css';
import '../css/sphereSection.css';
import '../css/scroll-sections-horisontal.css';
import '../css/navbar.css';
import './menuButon.js';
import '../css/heroSection.css';
